package com.szsyinfo.demo.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.szsyinfo.demo.db.CacheData;

import com.szsyinfo.demo.db.CacheDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cacheDataDaoConfig;

    private final CacheDataDao cacheDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cacheDataDaoConfig = daoConfigMap.get(CacheDataDao.class).clone();
        cacheDataDaoConfig.initIdentityScope(type);

        cacheDataDao = new CacheDataDao(cacheDataDaoConfig, this);

        registerDao(CacheData.class, cacheDataDao);
    }
    
    public void clear() {
        cacheDataDaoConfig.clearIdentityScope();
    }

    public CacheDataDao getCacheDataDao() {
        return cacheDataDao;
    }

}
